### PR TITLE
IPython 2.0 support (closes #7)

### LINKED ISSUE #7: Make bookstore work with new IPy2 notebook manager
Hi @rgbkrk, if you don't mind I am opening this to track what needs to be done.

[IPEP 16: Notebook multi directory dashboard and URL mapping](https://github.com/ipython/ipython/wiki/IPEP-16%3A-Notebook-multi-directory-dashboard-and-URL-mapping)

Use the source luke! [base class](https://github.com/ipython/ipython/blob/master/IPython/html/services/notebooks/nbmanager.py) [minimal implementation](https://github.com/khinsen/simple_notebook_manager/blob/master/lib/simple_notebook_manager.py)

Staying with OpenStack, do you think we can use object versioning for checkpoints?

### PR DESCRIPTION
**Pull request by andreabedini**
Hi @rgbkrk,

I thought about it and I think we should go with this code, here are some important changes:

- supports IPython 2.0 notebook manager api
- pyrax has been replaced by direct use of open swift client
- rackspace authentication will work only with username/password but not with the api key
- openstack credentials are fetched from the environment by default, like openstack utils do
- updated documentation

I understand the long term plan is to switch to libcloud so we should avoid referring to specific APIs. What do you think of renaming SwiftNotebookManager to simply NotebookManager?

[Review on Reviewable](https://reviewable.io/reviews/rgbkrk/bookstore/8)

### CODE REVIEW

**Comment by andreabedini** [comment]
it's been a while @rgbkrk! I have pushed my old work into a ipynb2 branch on this repository, I'll then delete my own repo. Feel free to do whatever you want with it :)

**Comment by rgbkrk** [comment]
Hey, thanks. Sorry this didn't go anywhere. The new OpenStackSDK is finally moving forward, I've been looking to touch this again once things stabilize (pyrax is deprecated for one).

**Comment by andreabedini** [comment]
next thing is a web native file manager that saves to github directly ;-) I'll let you start that :D

**Comment by rgbkrk** [comment]
Heh, you caught me on what I'd *rather* do.

**Comment by andreabedini** [comment]
I'm voting for you for president of the world

**Pull request closed without merging**
